### ISSUE TITLE
Rename to `presence`

### ISSUE THREAD

**Issue by max** [usecanvas/longhouse#10]
Projects that are part of our architecture should have simple and self-explanatory names that don't require asterisks.

We've built a presence service so let's call this project that.

**Comment by jclem** [comment]
Given that "presence" is a poor name to open source this project under, I'd like to come up with some way of having both of these.

**Comment by jclem** [comment]
Whether or not it's a poor name is up for debate, though. We can discuss when I'm back.

**Comment by max** [comment]
Yeh, I thought about that too. There is something to be said for a better brand when you open source things. It would be nice if we could find a middle ground. Apple does this well with `HomeKit`, `UIKit`, `HealthKit`. They brand them well but it's also somewhat obvious what each framework does.
